### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by ShynRou** [DistributedCollective/Sovryn-frontend#1496]
There are some general code issues that should be fixed and avoided in the future.

- [x] #1564
- [x] https://taiga.sovryn.app/project/sovryn-light/us/149
- [ ] https://taiga.sovryn.app/project/sovryn-light/us/148
- [x] removal of ts-ignore comments and fixing the underlying issues (#1570)
- [x] enable eslint rule @typescript-eslint/ban-ts-comment (#1570)
- [x] removal of eslint-disable comments where ever possible (#1578)
  Where it does not seem reasonable: make a note here so we can discuss changing the eslint-rules 
- [x] create a Code Guidelines document
